name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run lint
            - run: npm run checkfmt
            - run: npm run build
